name: Run scraper

on:
  push:
    paths:
    - 'src/bbc-weather-scraper.py'
  schedule:
    - cron: "0 */8 * * *"

jobs:
  scrape:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3 # Checkout branch into the runner

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
         
      - name: Run scraping script
        run:
          python src/bbc-weather-scraper.py
          
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull
          git add output/scrapes/
          git commit -m 'Update scraped data'
          git push
